repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: 'src/existing_code/getting_started\.py|src/existing_code/template_matching\.py|src/existing_code/rolling_mode\.py'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        exclude: 'src/existing_code/getting_started\.py|src/existing_code/template_matching\.py|src/existing_code/rolling_mode\.py'

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: 'src/existing_code/getting_started\.py'

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: Run Pytest
  #       entry: pytest
  #       language: system
  #       types: [python]
  #       files: ^test_code/.*\.py$
  #       pass_filenames: false



